main: be.maximvdw.warp.WarpPlugin
version: 1.0.0
name: Warp
website: http://dev.bukkit.org/bukkit-plugins/Warp/
author: Maximvdw
commands:
  warp:
    description: Teleport to a specific warp
  setwarp:
    description: Create a new warp
  warps:
    description: Warp configuration
  delwarp:
    description: Delete a warp
  setrndwarp:
    description: Create a new random warp
permissions:
  warp.*:
    description: Allows you to use all commands and warps